on: workflow_dispatch
name: Checkout code
jobs:
  web-deploy:
    name: :tada: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: :truck: Get latest code
      uses: actions/checkout@v2
    
    - name: :open_file_folder: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: i-glms.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: test-project/